const ACTIONS = {
  REQUEST_LAUNCHES: 'REQUEST_LAUNCHES',
  RECEIVE_LAUNCHES: 'RECEIVE_LAUNCHES',
  DISPLAY_LAUNCH_DETAILS: 'DISPLAY_LAUNCH_DETAILS',
  REQUEST_ROCKET_DETAILS: 'REQUEST_ROCKET_DETAILS',
  RECEIVE_ROCKET_DETAILS: 'RECEIVE_ROCKET_DETAILS'
};

export default ACTIONS;
